# Font
font-family = "Maple Mono NF CN"

# Theme
theme = "Glass Dark"
auto-theme-dark-mode = false

# Window
details-panel-width = 264

# Colors
foreground = "#f7f8ff"
background = "#40434b"
palette-0 = "#252a35"
palette-1 = "#ff8a8a"
palette-2 = "#a8d46f"
palette-3 = "#e8c778"
palette-4 = "#8db7ff"
palette-5 = "#d1a3ff"
palette-6 = "#7fd6c2"
palette-7 = "#e3e6f0"
palette-8 = "#747b8e"
palette-9 = "#ffb0a8"
palette-10 = "#c8ea90"
palette-11 = "#f2da9a"
palette-12 = "#b2ccff"
palette-13 = "#e0c2ff"
palette-14 = "#a3e6d8"
selection-background = "#bbc9ed"

# Transparency
background-opacity = 0.6

# Cursor
cursor-color = "#f7f8ff"
cursor-animation = "smooth"

# Mouse & Input
macos-option-as-alt = "left"
file-open-with = "otty"
folder-open-with = "otty"
omit-otty-prefix = true
open-with-app = "Zed|dev.zed.Zed"

# App Behavior
confirm-close-pane = "never"
